image: haskell:8

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

stages:
  - build
  - test

build:
  stage: build
  script:
    - stack build

unit-test:
  stage: test
  script:
    - stack
