name:                MicroRAM
version:             0.1.5.0
github:              "githubuser/MicroRAM"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MicroRAM#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-default
- haggle
- llvm-hs-pure
- llvm-hs
- mtl
- bytestring
- prettyprinter
- smallcheck
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-smallcheck
- transformers
- QuickCheck
- smallcheck
- utf8-string
- process
- split
- pptable # Pretty print Trace
- boxes
- aeson # Remove when not used anymore
- serialise
- cborg
- text
- filepath
- directory
- lens
- search-algorithms 
- vector
- data-binary-ieee754
- dom-lt
- parsec

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-orphans -Wno-name-shadowing -optP-Wno-nonportable-include-path

executables:
  compile:
    main:                Compile.hs
    source-dirs:         app
    ghc-options: 
    - -main-is Compile
    dependencies:
    - MicroRAM


tests:
  compiler:
    main:                Compiler/CompilerSpec.hs
    source-dirs:         test
    ghc-options:         
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Compiler.CompilerSpec
    dependencies:
    - MicroRAM
    - tasty
    - tasty-hunit
    - tasty-smallcheck
  interpreter:
    main:                InterpreterSpec.hs
    source-dirs:         test/MicroRAM
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is MicroRAM.InterpreterSpec
    dependencies:
    - MicroRAM
    - tasty
    - tasty-hunit
    - tasty-smallcheck
  post-process:
    main:                PostProcess/PostProcessSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PostProcess.PostProcessSpec
    dependencies:
    - MicroRAM
    - tasty
    - tasty-hunit
    - tasty-smallcheck
  output:
    main:                OutputSpec.hs
    source-dirs:         test/Output
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Output.OutputSpec
    dependencies:
    - MicroRAM
    - tasty
    - tasty-hunit
    - tasty-smallcheck
